@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!includeurl https://raw.githubusercontent.com/HomeMadeBots//Home_Temperature_Controller/main/doc/E_Setting_Mode.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots//Home_Temperature_Controller/main/doc/HTC_Setting_Mode.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots//Home_Temperature_Controller/main/doc/Setting_Manager_Class.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Button_Events/main/doc/Button_Pressed.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Time_Measurement/main/doc/Clock_Setting.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots//Home_Temperature_Controller/main/doc/Target_Home_Temperatures_Setting.puml

E_Setting_Mode <.. HTC_Setting_Mode : use
HTC_Setting_Mode <|..# "Setting_Mode" Setting_Manager_Class
Setting_Manager_Class "Increase_Setting_Button_Pressed\lDecrease_Setting_Button_Pressed\lNext_Setting_Button_Pressed\lPrevious_Setting_Button_Pressed" #..> Button_Pressed
Setting_Manager_Class "Clock_Setting" #..> Clock_Setting
Setting_Manager_Class "Temperature_Setting" #..> Target_Home_Temperatures_Setting

@enduml